import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const postsDir = path.join(__dirname, 'content', 'posts');
const outputPath = path.join(__dirname, 'moonbit', 'posts_data.mbt');

function parseFrontmatter(raw) {
  const match = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
  if (!match) {
    console.warn('Skipping file without valid frontmatter');
    return null;
  }

  const fm = match[1];
  const body = match[2].trim();

  const title = fm.match(/title:\s*"(.+?)"/)?.[1] || '';
  const date = fm.match(/date:\s*"(.+?)"/)?.[1] || '';
  const tagsMatch = fm.match(/tags:\s*\[(.+?)\]/);
  const tags = tagsMatch
    ? tagsMatch[1].split(',').map(t => t.trim().replace(/^"|"$/g, ''))
    : [];

  return { title, date, tags, body };
}

function escapeMoonBitString(s) {
  // JSON.stringify handles: \ → \\, " → \", newline → \n, tab → \t, etc.
  // Then unwrap the outer quotes since MoonBit needs the inner content
  return JSON.stringify(s).slice(1, -1);
}

function generateMoonBitFile(posts) {
  const items = posts.map(p => {
    const title = escapeMoonBitString(p.title);
    const url = `#${p.title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/-+$/, '')}`;
    const date = escapeMoonBitString(p.date);
    const tags = p.tags.map(t => `"${escapeMoonBitString(t)}"`).join(', ');
    const body = escapeMoonBitString(p.body);

    return `  BlogPost::{
    title: "${title}",
    url: "${url}",
    date: "${date}",
    tags: [${tags}],
    body: "${body}",
  }`;
  });

  return `///| This file is auto-generated by build-posts.js — do not edit manually.

pub fn posts_data() -> Array[BlogPost] {
  [
${items.join(',\n')}
  ]
}
`;
}

// --- Main ---

if (!fs.existsSync(postsDir)) {
  console.error(`Posts directory not found: ${postsDir}`);
  process.exit(1);
}

const files = fs.readdirSync(postsDir)
  .filter(f => f.endsWith('.md'))
  .sort()
  .reverse(); // newest first

const posts = [];

for (const file of files) {
  const raw = fs.readFileSync(path.join(postsDir, file), 'utf-8');
  const parsed = parseFrontmatter(raw);
  if (parsed) {
    posts.push(parsed);
    console.log(`  ✓ ${file} → "${parsed.title}"`);
  }
}

const output = generateMoonBitFile(posts);
fs.writeFileSync(outputPath, output);
console.log(`\nGenerated ${outputPath} (${posts.length} posts)`);
